services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app

      - backend_node_modules:/usr/src/app/backend/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
    command: sh -c "cd backend && npm install && npm run start:dev"
  postgres:
    image: postgres:15-alpine
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data:
  backend_node_modules: